run:
  go: '1.20'
  concurrency: 8
  deadline: 10m
  issues-exit-code: 1
  tests: false

skip-dirs:
  - api

linters-settings:
  depguard:
    list-type: blacklist
    include-go-root: true
    packages:
      # use "github.com/pkg/errors" instead
      - errors
      # use "github.com/golang/protobuf/proto" instead
      - github.com/gogo/protobuf/proto
      # use "gopkg.in/yaml.v3" instead
      - gopkg.in/yaml.v2
  exhaustive:
    default-signifies-exhaustive: true
  goimports:
    local-prefixes: gitlab.profitage.com/profitage/
  govet:
    check-shadowing: true
  cyclop:
    max-complexity: 30
  unparam:
    check-exported: true

linters:
  enable:
  - depguard
  - errcheck
  - gocritic
  - cyclop
  - gofmt
  - goimports
  - gosec
  - govet
  - ineffassign
  - misspell
  - nakedret
  - prealloc
  - exportloopref
  - staticcheck
  - stylecheck
  - unconvert
  - unparam
