run:
  go: '1.20'
  concurrency: 8
  timeout: 10m
  issues-exit-code: 1
  tests: false

linters-settings:
  depguard:
    rules:
      main:
        list-mode: lax
        files:
          - $all
        allow:
          - $gostd
          - github.com/OpenPeeDeeP/depguard/v2
        deny:
          - pkg: errors
            desc: use 'github.com/pkg/errors' instead
  exhaustive:
    default-signifies-exhaustive: true
  goimports:
    local-prefixes: github.com/teamdbnn
  govet:
    shadow: true
  cyclop:
    max-complexity: 30
  unparam:
    check-exported: true

linters:
  enable:
  - depguard
  - errcheck
  - gocritic
  - cyclop
  - gofmt
  - goimports
  - gosec
  - govet
  - ineffassign
  - misspell
  - nakedret
  - prealloc
  - exportloopref
  - staticcheck
  - stylecheck
  - unconvert
  - unparam
